In [42]:
import pandas as pd
import numpy as np

In [43]:
df = pd.read_csv('../data/warn.csv')

In [45]:
df.head()

,notice_date,event_number,reason,company,address,county,phone,business_type,affected,total_employees,layoff_date,dislocation,union,classification
0,4/30/2020,2019-1376,Temporary Plant Layoff,"Cast & Crew Payroll, LLC","7 Penn Plaza, Suite 601New York, NY 10001",New York County,(818) 848-6022,Payroll & HR Services,65,0,4/10/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Temporary Plant Layoff
1,4/30/2020,2019-1187,Plant Layoff,Michael Page International Inc.,"622 Third Avenue, 29th FloorNew York, NY 10017",New York County,(203) 905-5216,Employment Agency,97,97,4/8/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Plant Layoff
2,5/4/2020,2019-0278,Plant Layoff,"Jamestown Metal Products LLC, a division of In...","178 Blackstone AvenueJamestown, NY 14701",Chautauqua County,(731) 642-4251 Ext,Provide complete source for lab systems and su...,37,77,Separations,Economic,International Association of Machinists and Ae...,Plant Layoff
3,5/1/2020,2019-1214,Temporary Plant Closing,Westbury Manor Enterprises Inc.,"1100 Jericho TurnpikeWestbury, NY 11590",Nassau County,(516) 333-7117,Restaurant,123,123,3/22/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Temporary Plant Closing
4,4/30/2020,2019-0377,Plant Closing,"Altman Lighting, Inc.","57 Alexander StreetYonkers, NY 10701",Westchester County,(303) 558-4300 Ext,"Theatrical, architectural, film and video ligh...",46,46,45,Relocation to Colorado,The employees are not represented by a union.,Plant Closing

In [46]:
df.tail()

,notice_date,event_number,reason,company,address,county,phone,business_type,affected,total_employees,layoff_date,dislocation,union,classification
1231,1/8/2020,2019-0210,Plant Closing,"Connected Ventures, LLC (CH Media)","330 W. 34th Street, 5th FloorNew York, NY 10001",New York County,(212) 314-7366,Operates online content and retail properties,39,39,Employment,Economic,The employees are not represented by a union.,Plant Closing
1232,1/6/2020,2019-0207,Plant Closing,Macy's Broadway Mall Store (Macy's Retail Hold...,"100 Broadway MallHicksville, NY 11801",Nassau County,(646) 429-7462,Retail Store,155,155,Macy's,Economic,The employees are not represented by a union.,Plant Closing
1233,12/27/2019,2019-0206,Temporary Plant Closing,Wesley Gardens Nursing Home,"3 Upton ParkRochester, NY 14607",Monroe County,(585) 241-2105,Nursing Home,132,132,Beginning,Due to a water line break,1199 SEIU,Temporary Plant Closing
1234,12/30/2019,2019-0205,Plant Closing,"127 W. 43rd St. Chophouse, Inc. (Heartland Bre...","127 West 43rd StreetNew York, NY 10018",New York County,(917) 999-6532,Restaurant,106,106,The,Economic,The employees are not represented by a union.,Plant Closing
1235,12/30/2019,2019-0201,Plant Closing,"New York Express and Logistics, LLC","292 Wolf RoadLatham, NY 12110",Albany County,(617) 968-5311,Trucking company providing freight transportat...,48,48,3/31/2020,Contract between New York Express and Logistic...,The employees are not represented by a union.,Plant Closing

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1236 entries, 0 to 1235
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   notice_date      1236 non-null   object
 1   event_number     1236 non-null   object
 2   reason           1236 non-null   object
 3   company          1236 non-null   object
 4   address          1235 non-null   object
 5   county           1236 non-null   object
 6   phone            1236 non-null   object
 7   business_type    1236 non-null   object
 8   affected         1236 non-null   object
 9   total_employees  1236 non-null   int64
 10  layoff_date      1233 non-null   object
 11  dislocation      1236 non-null   object
 12  union            1236 non-null   object
 13  classification   1236 non-null   object
dtypes: int64(1), object(13)
memory usage: 135.3+ KB

In [112]:
df.to_csv('../data/warn_na.csv', index=False)

In [113]:
df_na = pd.read_csv('../data/warn_na.csv')

In [114]:
df_na.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1236 entries, 0 to 1235
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   notice_date      1236 non-null   object
 1   event_number     1236 non-null   object
 2   reason           1236 non-null   object
 3   company          1236 non-null   object
 4   address          1236 non-null   object
 5   county           1236 non-null   object
 6   phone            1236 non-null   object
 7   business_type    1236 non-null   object
 8   affected         1236 non-null   object
 9   total_employees  1236 non-null   int64
 10  layoff_date      1236 non-null   object
 11  dislocation      1236 non-null   object
 12  union            1236 non-null   object
 13  classification   1236 non-null   object
dtypes: int64(1), object(13)
memory usage: 135.3+ KB

In [115]:
df = df.fillna(0)

In [144]:
df_na.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1236 entries, 0 to 1235
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   notice_date      1236 non-null   object
 1   event_number     1236 non-null   object
 2   reason           1236 non-null   object
 3   company          1236 non-null   object
 4   address          1236 non-null   object
 5   county           1236 non-null   object
 6   phone            1236 non-null   object
 7   business_type    1236 non-null   object
 8   affected         1236 non-null   object
 9   total_employees  1236 non-null   int64
 10  layoff_date      1236 non-null   object
 11  dislocation      1236 non-null   object
 12  union            1236 non-null   object
 13  classification   1236 non-null   object
dtypes: int64(1), object(13)
memory usage: 135.3+ KB

In [75]:
#Which kind of reasons of WARN notifications were the most?
df_na['reason'].unique()

array(['Temporary Plant Layoff', 'Plant Layoff',
       'Temporary Plant Closing', 'Plant Closing', 'Plang Closing',
       'Temporary Layoff', 'Temporary Plant Closing and Plant Closing',
       'Temporary & Permanent Layoff', 'Temporary Plant \nClosing',
       'Temporary Plant \nLayoff',
       'Temporary Plant Layoff and Plant Closing',
       'Temporary Reduction in Work Hours',
       'Temporary Plant Layoff/Plant Layoff',
       'Temporary Plant Layoff (Furlough)', 'Plant Layoff (Conditional)',
       'Temporary PLant Layoff', 'Temporary PlantClosing',
       'Temporary Closing', 'Possible Plant Layoff/Closing',
       'Temporary Palnt Closing', 'Plant Temporary Closing', 'Plant Sale',
       'Contract Dissolution', 'Plant Unit Closing',
       'Tempoarary Plant Closing', 'Plant Relocation',
       'Partial Temporary Closing', 'Temporary Plant Layoff/Closing',
       'Plant Demolition', 'Temporary Partial Plant Closing',
       'Temporary Plant Closing/Layoff', 'TemporaryPlant Closing',
       'Temporary Unit Closing', 'Temporary Plant  Closing',
       'Temporary  Plant Layoff', 'Temporary  Plant Closing',
       'Temporary Plant  Layoff'], dtype=object)

In [153]:
Reason = df_na['reason'].value_counts()
Reason

Temporary Plant Layoff                       604
Temporary Plant Closing                      463
Plant Closing                                 83
Plant Layoff                                  73
Plant Relocation                               1
Contract Dissolution                           1
Temporary Partial Plant Closing                1
Temporary Plant Closing/Layoff                 1
Plant Sale                                     1
Temporary Plant Layoff and Plant Closing       1
Plang Closing                                  1
Temporary Plant Closing and Plant Closing      1
Plant Demolition                               1
Temporary & Permanent Layoff                   1
Temporary Plant Layoff/Closing                 1
Temporary Reduction in Work Hours              1
Possible Plant Layoff/Closing                  1
Name: reason, dtype: int64

In [154]:
df.loc[df['reason'].isin(['Temporary PlantClosing', 
                          'TemporaryPlant Closing', 
                          'Temporary Plant \nClosing',
                          'Temporary Plant  Closing',
                          'Temporary Palnt Closing',
                          'Temporary Closing',
                          'Temporary  Plant Closing', 
                          'Temporary Unit Closing',
                          'Plant Temporary Closing',
                          'Temporary Plant Closing and Plant Closing'
                          'Temporary Partial Plant Closing',
                          'Partial Temporary Closing',
                          'Tempoarary Plant Closing']), 'reason'] = 'Temporary Plant Closing' 
df.loc[df['reason'].isin(['Temporary Plant  Layoff', 
                          'Temporary PLant Layoff', 
                          'Temporary  Plant Layoff',
                          'Temporary Plant Layoff/Plant Layoff',
                          'Temporary Plant Layoff (Furlough)',
                          'Temporary Plant \nLayoff',
                          'Temporary Layoff'
                          ]), 'reason'] = 'Temporary Plant Layoff'
df.loc[df['reason'].isin(['Plant Unit Closing']), 'reason'] = 'Plant Closing'
df.loc[df['reason'].isin(['Plant Layoff (Conditional)',
                          'Possible Plant Layoff']), 'reason'] = 'Plant Layoff'

In [155]:
reasons = df_na['reason'].value_counts().reset_index().rename(columns = {'index': 'reason', 'reason': 'count'})
reasons

                                       reason  count
0                      Temporary Plant Layoff    604
1                     Temporary Plant Closing    463
2                               Plant Closing     83
3                                Plant Layoff     73
4                            Plant Relocation      1
5                        Contract Dissolution      1
6             Temporary Partial Plant Closing      1
7              Temporary Plant Closing/Layoff      1
8                                  Plant Sale      1
9    Temporary Plant Layoff and Plant Closing      1
10                              Plang Closing      1
11  Temporary Plant Closing and Plant Closing      1
12                           Plant Demolition      1
13               Temporary & Permanent Layoff      1
14             Temporary Plant Layoff/Closing      1
15          Temporary Reduction in Work Hours      1
16              Possible Plant Layoff/Closing      1

In [156]:
reasons.to_csv('../data/reasons.csv', index=False)

In [157]:
#Which kind of business types were affected by a WARN notice most? Select>10
df['business_type'].unique()

array(['Payroll & HR Services', 'Employment Agency',
       'Provide complete source for lab systems and sustainable, adaptable casework of painted steel, wood or stainless steel complete with specified fixtures, fume hoods and work surfaces.',
       'Restaurant', 'Theatrical, architectural, film and video lighting',
       'Hotel', 'Commercial Printing', 'American online travel company',
       'Building maintenance and cleaning services', 'Event Company',
       'Car cleaning services', 'Realty Management', 'Seafood Restaurant',
       'All Luxury SUV, Cars, Vans Rentals', 'Car rentals',
       'Dental equipment distribution and manufacturing',
       'On-demand car service', 'Renewable Energy Provider',
       'Event Planners/Caterers', 'Transporation Services',
       'Quality cleaning and maintenance services', 'Car Rentals',
       'Transportation', 'Marine Cargo Handling',
       'Producer of LED safety lighting', 'Car Rental', 'Travel Agency',
       'Family planning services', 'Retail', 'Janitorial Services',
       'Gem Research, Education, and Laboratory', 'Labor Union',
       'Non-profit', 'Medical Billing', 'Event Venue',
       'Convention Center', 'Social Organization', 'Cinemas', 'Catering',
       'Mechanical Contractor', 'Social Club', 'Human Services',
       'Wine Wholesaler', 'General Contractor', 'Production Company',
       'Janitorial Engineering', 'Fitness Club', 'Legal Services',
       'Shoe Store', 'Carpentry Organization',
       'Lumber and Building Material Distribution',
       'Transportation Carrier', 'Food preparation and delivery services',
       'Outdoor Lounge/Restaurant', 'Bakery', 'Eye Care',
       'Plumbing, Heating, PVF, Waterworks, and Fire Protection Supplies',
       'Plumbing, Heating, PVF, Fire Protection, and Waterworks Supplies',
       'Manufacturing', 'Day Camp', 'Airline Services',
       'Healthcare Center', 'Home automation',
       'Miscellaneous Home Furnishings Store', 'Rental Car',
       'Plumbing and Heating',
       'Visual Effects and Post Production Services',
       'Commercial Real Estate Services', 'Medical Facility',
       'Interior Design', 'Retail Store', 'Health Care',
       'Wafer fab, assembly, and test operations', 'School',
       'Air Compressor Manufacturer', 'Diagnostic Imaging Center',
       'Waste Services and Material Recycling', 'Security Services',
       'Airport Services', 'Cosmetic Manufacturing',
       'Cosmetic Manufacturer', 'Environmental Consulting',
       'Medical Laboratory', 'Building Services', 'Electric Company',
       'Provides ground, cargo and passenger services', 'Bank',
       'Movie Theatre', 'PR Consulting',
       'Human services non-profit organization sponsored by the Catholic Charities of the Archdiocese of New York with programs that help a large needy population in the New York metropolitan area.',
       'Theater', 'Wholesale Distribution', 'Travel and Tourism',
       'Clothing Retail', 'Consulting Group', 'Auto Dealership',
       'Communication, Public Relations', 'Solar Energy Equipment',
       'Media Company', 'Sheet Metal Contractor',
       'Executive Events Company', 'Retail clothing store',
       'Same-day grocery delivery and pick-up service', 'Manufacturer',
       'Internet Retail', 'Broth Shop',
       'Designer, Distribution and Licensor of Apparel', 'Museum',
       'Suit Retail', 'Fiberglass Manufacturing', 'Travel Center',
       'Consumer Electronics Company', 'Moulding Wholesaler',
       'Medical Imaging', 'Electrical Contracting', 'Airline',
       'Cleaning Services', 'Realty', 'Home Health Care', 'Auction House',
       'Computer Networking', 'Concrete Supplier', 'Cement Plant',
       'Transportation and Logistics', 'Investment Services', 'Auto Shop',
       'Ophthalmologist/Optician', 'Ophthalmologist', 'Dentist',
       'Paper Retailer', 'Musical Instrument Sales',
       'Aviation consultant', 'Leather Wholesaler', 'Software Company',
       'Asphalt Contractor', 'Community Working Space', 'Adolescent Care',
       'Public relations', 'Theatre Company', 'Movie Theater',
       'Accounting and Financial Services', 'Countertop Sales',
       'Car dealership', 'Custom fabricator of architectural metal',
       'Auto dealership', 'Auto Body Shop',
       'Fire Prevention/Sprinkler Services', 'Auto Sales', 'Hunting Club',
       'Financial Institution', 'Marketing', 'Optical Retailer',
       'Ski Resort', 'Cleaning and Flooring', 'Hydraulic Repair Service',
       'Iron Manufacturer', 'Contracting', 'Courier Service',
       'Façade Manufacturing', 'Duck Farming', 'Online Fitness',
       'Online Recommendations', 'Commercial real estate company',
       'Excavation, Pile Drilling, and Foundations', 'Pool Manufacturer',
       'Country Club', 'Building Materials Supplier',
       'Obstetrics and Gynecology', 'Heating and Cooling',
       'Limousine Service', 'Gym', 'Orthopedics', 'Jewelry Sales',
       'Network Provider', 'Airport Restaurant', 'Bus Transit',
       'Clothing Manufacturer', 'Excavating Contractor',
       'Plastic Manufacturing', 'Footwear Retailer',
       'Bedding, Bath, and window Manufacturing',
       'Supply Chain Management', 'Mechanical Systems Building',
       'Insulation Contractor', 'Furniture', 'Collision Repair',
       'Community Center', 'Stone Quarry', 'Linen and Uniforms',
       'Architectural Metal and Glass Manufacturing',
       'Water Manufacturer', 'Contracting Company', 'Duck Farm',
       'Digital Marketing', 'Musical Instrument Rental', 'Day Spa',
       'Attorney', 'Golf Course', 'Event Planning',
       'Electronic Instrument Manufacturer', 'Animal Feed Store',
       'Neurology Health Care Provider', 'Collection Agency',
       'Youth Club', 'Wholesale Bakery', 'Beauty Salon Equipment',
       'Auto Dealer', 'Law Firm', 'Tree service',
       'Security System Installation', 'Closets and Storage',
       'Watch, Guard, Patrol Agency', 'Optometry Offices',
       'Global tech media company', 'Footwear',
       'Parking Service/Locations', 'Commercial Cleaning',
       'Architecture Firm', 'Art Storage and Services', 'Electricians',
       'Custom auto interior parts for classic car restoration',
       'Go-kart track', 'Industrial Machinery & Equipment',
       "Attorney's Office", 'Promotional Product Supplier',
       'Casino Hotel', 'Waxing Services', 'Electrical Supply Store',
       'Health Care Provider - Mammography', 'Education and Child Care',
       'Transportation Company', 'Refrigeration Wholesaler',
       'Sporting Goods', 'Fire Sprinkler Installation',
       'Studio Equipment', 'Physcial and Occupational Therapy',
       'Physical and Occupational Therapy', 'Undergarments',
       'Machine Shop', 'Linen and Uniform Supply',
       'Retail & Light Manufacturing', 'Social services organization',
       'Clothing Store', 'Cellular Sales', 'Call Center', 'Toy Store',
       'an American clothing brand and retailer',
       'Modern Japanese restaurant', 'Music Venue', 'Satellite Supplies',
       'Resort Hotel', 'Linen Supply', 'Emergency Relief',
       'Wellness Center', 'Food Distribution', 'Real Estate',
       'Medical Equipment', 'Portfolio Management', 'Construction',
       'Real Estate Manager and Developer', 'Coffee Shop',
       'Meat Wholesaler', 'Car Dealership', 'Home Furnishing',
       'Sanitation', 'Consulting', 'Animal Wellness and Care',
       'Data Analytics Service Provider', 'Carpet Cleaning Service',
       'Integrated Media Entertainment', 'Ticket Sales', 'Software',
       'Ambulatory Surgery Center', 'Catering Staffing', 'Hospitality',
       'Audio, Visual and Lighting', 'Denim Retailer',
       'Watch Manufacturing', 'Airport Retail', 'Party Rental',
       'Childhood Center', 'Airline Security', 'Award Manufacturer',
       'Automobile Sales', 'Logistics and Supply Chain Solutions',
       'Mattress Store', 'Winter Sports Center', 'Motor Vehicle Sales',
       'Furniture Store', 'Physcial Therapist', 'Human Services Agency',
       'Telemarketing', 'Debt Collection', 'Healthcare',
       'Waste disposal and removal services', 'Jewelry Store',
       'Perfume Manufacturing', '-----', 'Advertising', 'Hair Salon',
       'Leading global IT services company', 'Amusement Machine Supplier',
       'Hotel and Restaurant', 'Resort', 'Fragrance Manufacturing',
       'Airline Sales', 'Catering/Event Venue', 'Daycare',
       'Clothing Manufacturing', 'Creamery', 'Salon', 'Venue',
       'Airport Support', 'Education', 'Distribution',
       'Interior designer', 'French Restaurant',
       'Performing Arts Theater', 'Photographic equipment and Supplies',
       'Health group practice', 'Production  Company',
       'Catering business',
       'Providing temporary and long-term housing accommodations for relocated individuals and corporate officials',
       'Manages the production and distribution for Gannett’s domestic daily newspapers',
       'Pharmaceuticals (production)', 'Manufacturer of capacitors',
       'A 675-megawatt coal-fired power plant',
       'A global defense technology leader',
       'Paratransit transportation throughout the 5 boroughs of New York City.',
       'Acute Care Hospital',
       'Produces  and distributes numerous brands of bottled water across North America.',
       'Viacom operates as an entertainment media company that offers television programs and motion pictures.',
       'Parking facility servicing the LaGuardia Airport',
       'Programs for persons with development disabilities.',
       'Wholesale grocer', 'Transportation Services',
       'Drug distribution company',
       'Members-only personal shopping and concierge service',
       'Developing private incubated brands across multiple categories of Health, Beauty, & Wellness, Fashion, and Home furnishing products.',
       'Retail Corporate offices', 'Banking  Services',
       'Wholesale distributor of Janitorial and Industrial Supplies',
       'Providing investment management and research services',
       'Retail  and auto store', 'Retail store', 'Daily newspaper',
       'Leading  healthcare improvement company',
       'New York City-based online monthly subscription service that sends its subscribers a box of four to five selected samples of makeup, or other beauty related products..',
       'Clinical Services', 'General Medical & Surgical Hospital',
       'Health and fitness center',
       'Human services non-profit organization with programs that help a large needy population in the New York metropolitan area.',
       'Manufacturer of air & gas compressors',
       'American premium channel owned by the Home Box Office, Inc.',
       'Non-profit organization', 'Health Plans', 'Publishing company',
       'LawFirm', 'Hobby, Toy, and Game Stores',
       'Welding and Soldering Equipment Manufacturing',
       'Operates online content and retail properties', 'Nursing Home',
       'Trucking company providing freight transportation services and hauling cargo'],
      dtype=object)

In [170]:
business_type = df['business_type'].value_counts().reset_index()
business_type

                                  index  business_type
0                            Restaurant            482
1                                 Hotel            141
2                                Retail             39
3                       Auto Dealership             24
4                              Catering             16
..                                  ...            ...
358   Accounting and Financial Services              1
359                     Airport Support              1
360              Transporation Services              1
361  Health Care Provider - Mammography              1
362                            Day Camp              1

[363 rows x 2 columns]

In [171]:
business_type.to_csv('../data/business_type.csv', index=False)

In [172]:
business_type.sort_values("business_type", ascending=False)

                                                 index  business_type
0                                           Restaurant            482
1                                                Hotel            141
2                                               Retail             39
3                                      Auto Dealership             24
4                                             Catering             16
..                                                 ...            ...
169                              Human Services Agency              1
168                             Online Recommendations              1
167  Trucking company providing freight transportat...              1
166                                         Youth Club              1
362                                           Day Camp              1

[363 rows x 2 columns]

In [173]:
business_type.head(10)

                   index  business_type
0             Restaurant            482
1                  Hotel            141
2                 Retail             39
3        Auto Dealership             24
4               Catering             16
5               Eye Care             10
6      Building Services             10
7  Retail clothing store             10
8         Transportation              8
9                 School              7

In [179]:
#Which kind of reason for diclocations of WARN notifications were the most? Select>1
dislocations = df_na['dislocation'].value_counts().reset_index().rename(columns={'index': 'dislocation', 'dislocation': 'count'})
dislocations

                                          dislocation  count
0   Unforeseeable business circumstances prompted ...   1108
1                                            Economic     57
2   Unforeseeable  business circumstances prompted...      8
3   Unforeseen business circumstances as a result ...      3
4   Restructuring which will involve the relocatio...      3
5   The Company’s initial temporary layoffs were u...      3
6                                    Sale of Business      3
7   EconomicUnforeseeable business circumstances p...      2
8                                   Budgetary Deficit      2
9   Economic and unforeseen business circumstances...      1
10  The production work is moving to another compa...      1
11                               Sale of the business      1
12                             Company Reorganization      1
13                                     Reorganization      1
14                                      Contract Loss      1
15  School closing mandated by the State of New Yo...      1
16                                   Loss of Contract      1
17                  Relocating facility to Minnesota.      1
18                      Discontinuation of operations      1
19           Restructure of the New York Metro market      1
20  Newspaper production will be consolidated to t...      1
21  Landlord's decision to cease operating the par...      1
22  The Company’s initial temporary layoffs were u...      1
23  They are integrating many of these incubated b...      1
24  Due to an operational change to optimize the R...      1
25  Reduction in workload due to a change in busin...      1
26  GNYHA Management Corporation has announced the...      1
27  The decision was made to integrate conversatio...      1
28  Sale of heritage Dresser-Rand / SGT Government...      1
29                             Relocation to Colorado      1
30              Maria Russo, Human Resources Director      1
31   Loss of Contract with New York Transit Authority      1
32                                   Sale of business      1
33                       Expiration of building lease      1
34  Economic and stricter new State air emission r...      1
35  Unforeseen business circumstances as a result ...      1
36  Early contract termination by Maersk Lines. Th...      1
37                      Acquisition by Community Bank      1
38                                Expiration of lease      1
39              Sale of business to Republic Services      1
40                                    Sale of Company      1
41  Winding down its in-store operations across Fa...      1
42  Contract termination by Metropolitan Transit A...      1
43  Merger with Troutman Sanders and to become kno...      1
44                          Due to a water line break      1
45  Death of Company President and Unforeseeable b...      1
46  Due to a substantial loss of contract funding ...      1
47  The contract between Swissport and the Port Au...      1
48  Sale of the business to a buyer who is relocat...      1
49                                         Relocation      1
50  The MTA did not renew contract which expires M...      1
51  Consolidation of revenue cycle functions/closu...      1
52  Catholic Guardian Services has decided to disc...      1
53  Contract between New York Express and Logistic...      1
54  Relocation of Corporate Headquarters to Nashvi...      1
55                                    Loss of funding      1

In [181]:
dislocations.to_csv('../data/dislocations.csv', index=False)

In [183]:
dislocations.head(15)

                                          dislocation  count
0   Unforeseeable business circumstances prompted ...   1108
1                                            Economic     57
2   Unforeseeable  business circumstances prompted...      8
3   Unforeseen business circumstances as a result ...      3
4   Restructuring which will involve the relocatio...      3
5   The Company’s initial temporary layoffs were u...      3
6                                    Sale of Business      3
7   EconomicUnforeseeable business circumstances p...      2
8                                   Budgetary Deficit      2
9   Economic and unforeseen business circumstances...      1
10  The production work is moving to another compa...      1
11                               Sale of the business      1
12                             Company Reorganization      1
13                                     Reorganization      1
14                                      Contract Loss      1

In [185]:
df_na[df_na.affected != 'To']

,notice_date,event_number,reason,company,address,county,phone,business_type,affected,total_employees,layoff_date,dislocation,union,classification
0,4/30/2020,2019-1376,Temporary Plant Layoff,"Cast & Crew Payroll, LLC","7 Penn Plaza, Suite 601New York, NY 10001",New York County,(818) 848-6022,Payroll & HR Services,65,0,4/10/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Temporary Plant Layoff
1,4/30/2020,2019-1187,Plant Layoff,Michael Page International Inc.,"622 Third Avenue, 29th FloorNew York, NY 10017",New York County,(203) 905-5216,Employment Agency,97,97,4/8/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Plant Layoff
2,5/4/2020,2019-0278,Plant Layoff,"Jamestown Metal Products LLC, a division of In...","178 Blackstone AvenueJamestown, NY 14701",Chautauqua County,(731) 642-4251 Ext,Provide complete source for lab systems and su...,37,77,Separations,Economic,International Association of Machinists and Ae...,Plant Layoff
3,5/1/2020,2019-1214,Temporary Plant Closing,Westbury Manor Enterprises Inc.,"1100 Jericho TurnpikeWestbury, NY 11590",Nassau County,(516) 333-7117,Restaurant,123,123,3/22/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Temporary Plant Closing
4,4/30/2020,2019-0377,Plant Closing,"Altman Lighting, Inc.","57 Alexander StreetYonkers, NY 10701",Westchester County,(303) 558-4300 Ext,"Theatrical, architectural, film and video ligh...",46,46,45,Relocation to Colorado,The employees are not represented by a union.,Plant Closing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1231,1/8/2020,2019-0210,Plant Closing,"Connected Ventures, LLC (CH Media)","330 W. 34th Street, 5th FloorNew York, NY 10001",New York County,(212) 314-7366,Operates online content and retail properties,39,39,Employment,Economic,The employees are not represented by a union.,Plant Closing
1232,1/6/2020,2019-0207,Plant Closing,Macy's Broadway Mall Store (Macy's Retail Hold...,"100 Broadway MallHicksville, NY 11801",Nassau County,(646) 429-7462,Retail Store,155,155,Macy's,Economic,The employees are not represented by a union.,Plant Closing
1233,12/27/2019,2019-0206,Temporary Plant Closing,Wesley Gardens Nursing Home,"3 Upton ParkRochester, NY 14607",Monroe County,(585) 241-2105,Nursing Home,132,132,Beginning,Due to a water line break,1199 SEIU,Temporary Plant Closing
1234,12/30/2019,2019-0205,Plant Closing,"127 W. 43rd St. Chophouse, Inc. (Heartland Bre...","127 West 43rd StreetNew York, NY 10018",New York County,(917) 999-6532,Restaurant,106,106,The,Economic,The employees are not represented by a union.,Plant Closing
1235,12/30/2019,2019-0201,Plant Closing,"New York Express and Logistics, LLC","292 Wolf RoadLatham, NY 12110",Albany County,(617) 968-5311,Trucking company providing freight transportat...,48,48,3/31/2020,Contract between New York Express and Logistic...,The employees are not represented by a union.,Plant Closing

In [187]:
df_na.head(35)

,notice_date,event_number,reason,company,address,county,phone,business_type,affected,total_employees,layoff_date,dislocation,union,classification
0,4/30/2020,2019-1376,Temporary Plant Layoff,"Cast & Crew Payroll, LLC","7 Penn Plaza, Suite 601New York, NY 10001",New York County,(818) 848-6022,Payroll & HR Services,65,0,4/10/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Temporary Plant Layoff
1,4/30/2020,2019-1187,Plant Layoff,Michael Page International Inc.,"622 Third Avenue, 29th FloorNew York, NY 10017",New York County,(203) 905-5216,Employment Agency,97,97,4/8/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Plant Layoff
2,5/4/2020,2019-0278,Plant Layoff,"Jamestown Metal Products LLC, a division of In...","178 Blackstone AvenueJamestown, NY 14701",Chautauqua County,(731) 642-4251 Ext,Provide complete source for lab systems and su...,37,77,Separations,Economic,International Association of Machinists and Ae...,Plant Layoff
3,5/1/2020,2019-1214,Temporary Plant Closing,Westbury Manor Enterprises Inc.,"1100 Jericho TurnpikeWestbury, NY 11590",Nassau County,(516) 333-7117,Restaurant,123,123,3/22/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Temporary Plant Closing
4,4/30/2020,2019-0377,Plant Closing,"Altman Lighting, Inc.","57 Alexander StreetYonkers, NY 10701",Westchester County,(303) 558-4300 Ext,"Theatrical, architectural, film and video ligh...",46,46,45,Relocation to Colorado,The employees are not represented by a union.,Plant Closing
5,5/4/2020,2019-1606,Temporary Plant Closing,"Hartz Hotel Services, Inc. (manager of The Rox...","2 Avenue of the AmericasNew York, NY 10013",New York County,(201) 272-5800,Hotel,79,79,5/15/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Closing
6,5/5/2020,2019-1607,Plant Closing,RR Donnelley (TuckerPrinters facility),"270 Middle Rd.Henrietta, NY 14467",Monroe County,(716) 564-6469,Commercial Printing,33,33,5/5/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Plant Closing
7,4/28/2020,2019-1612,Plant Layoff,TripAdvisor LLC,"17 Battery PlaceNew York, NY 10004",New York County,(781) 800-5341,American online travel company,36,36,5/5/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Plant Layoff
8,4/15/2020,2019-1613,Temporary Plant Layoff,"PBM, LLC (Perfect Building Maintenance)","405 Lexington Avenue, 40th FloorNew York, NY 1...",New York County,(212) 244-3434,Building maintenance and cleaning services,349,0,3/9/2020,Unforeseeable business circumstances prompted ...,Local 32BJ SEIU,Temporary Plant Layoff
9,4/27/2020,2019-1507,Temporary Plant Layoff,Production Glue LLC,"252 W. 37th Street, Floor 7New York, NY 10018",New York County,(917) 304-3124,Event Company,49,0,3/27/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Temporary Plant Layoff
10,4/27/2020,2019-1608,Temporary Plant Closing,Hoffman Car Wash,Multiple Capital Region locations,Albany/Warren/Saratoga County,(518) 389-2123,Car cleaning services,352,352,3/23/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Closing
11,4/27/2020,2019-1610,Temporary Plant Closing,Hoffman Car Wash,"1091 Ulster Ave.Kingston, NY 12401",Ulster County,(518) 389-2123,Car cleaning services,36,36,3/23/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Closing
12,3/27/2020,2019-1614,Temporary Plant Layoff,"William Gottlieb Management Co., LLC","177 Christopher StreetNew York, NY 10014",New York County,(212) 989-3100,Realty Management,41,0,3/27/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Layoff
13,4/27/2020,2019-1611,Temporary Plant Closing,Hoffman Car Wash,"2524 Vestal ParkwayVestal, NY 13850",Broome County,(518) 389-2123,Car cleaning services,14,14,3/23/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Closing
14,4/27/2020,2019-1609,Temporary Plant Closing,Hoffman Car Wash,Amsterdam CarWash - 4858 State Highway 30Amste...,Montgomery County,(518) 389-2123,Car cleaning services,5,5,3/23/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Closing
15,5/1/2020,2019-1597,Plant Closing,"Aqua Grill, Inc.","210 Spring StreetNew York, NY 10012",New York County,(212) 274-0505,Seafood Restaurant,65,65,3/16/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Plant Closing
16,3/20/2020,2019-1598,Temporary Plant Layoff,Go Rentals,"184 Airport RdWhite Plains, NY 10604",Westchester County,(949) 222-1900 Ext,"All Luxury SUV, Cars, Vans Rentals",4,0,Separations,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Layoff
17,4/29/2020,2019-1599,Plant Layoff,Enterprise Holdings,"Building 69 Federal CircleJamaica, NY 11430",Queens County,(929) 372-7900,Car rentals,174,174,The,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Plant Layoff
18,4/30/2020,2019-1567,Plant Layoff,"Crosstex International, Inc. (Cantel) Phase 6","10 Ranick RoadHauppauge, NY 11788",Suffolk County,(847) 257-4740,Dental equipment distribution and manufacturing,1,77,Separation,Restructuring which will involve the relocatio...,The employees are not represented by a union.,Plant Layoff
19,5/5/2020,2019-1625,Plang Closing,"Marriott Hotel Services, Inc. dba New York Mar...","525 Lexington AvenueNew York, NY 10017",New York County,(908) 482-1075,Hotel,316,316,Separations,Unforeseeable business circumstances prompted ...,"New York Hotel & Motel Trades Council, AFL-CIO",Plant Closing
20,5/7/2020,2019-1626,Plant Layoff,"Uber Technologies, Inc.","31-00 47th AvenueLong Island City, NY 11101",Queens County,(630) 715-1006,On-demand car service,26,0,6/5/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Plant Layoff
21,5/4/2020,2019-1602,Temporary Plant Layoff,"NRG Energy, Inc. (Green Mountain Energy NYC Of...","16 Madison Square Park West, 12th FloorNew Yor...",New York County,(713) 537-2187,Renewable Energy Provider,71,0,Beginning,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Layoff
22,5/4/2020,2019-1603,Temporary Plant Closing,"CPS5, LLC (CPS Events at the Plaza)","770 5th AvenueNew York, NY 10019",New York County,(646) 265-6952,Event Planners/Caterers,125,125,3/16/2020,Unforeseeable business circumstances prompted ...,"New York Hotel & Motel Trades Council, AFL-CIO...",Temporary Plant Closing
23,4/30/2020,2019-1604,Temporary Plant Closing,"JAD Transportation, Inc. Twin America, LLC, R....","1430 Broadway, Suite 507New York, NY 10018",New York County,(212) 235-5850,Transporation Services,550,550,3/18/2020,Unforeseeable business circumstances prompted ...,"United Service Workers Union, Local 1212, the ...",Temporary Plant Closing
24,5/4/2020,2019-1605,Temporary Plant Closing,"Hartz Hotel Services, Inc. (manager of the Soh...","310 W. BroadwayNew York, NY 10013",New York County,(201) 272-5800,Hotel,109,109,5/15/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Closing
25,4/17/2020,2019-1591 – 2019-1596,Temporary Plant Layoff,"Eat'n Park Hospitality Group, Inc. (Parkhurst ...",(Multiple Region sites),Chemung County,(412) 461-2000 Ext,Restaurant,180,180,Separations,Unforeseeable business circumstances prompted ...,"CSEA, Local 1000",Temporary Plant Layoff
26,5/1/2020,2019-1589,Plant Layoff,"Collins Building Services, Inc.",Multiple New York City and Long Island sites,New York/Kings County,(212) 896-5100,Quality cleaning and maintenance services,435,495,Employee,Unforeseeable business circumstances prompted ...,Realty Advisory Board and SEIU Local 32BJ,Plant Layoff
27,4/14/2020,2019-1588,Plant Layoff,Hertz,John F Kennedy International Airport312 Federa...,New York/Queens County,(239) 301-7018,Car Rentals,78,78,Separations,Unforeseeable business circumstances prompted ...,"IBT, Local 272 and IAM, District 15",Plant Layoff
28,4/30/2020,2019-1587,Temporary Plant Layoff,"All County Bus, LLC","70 Fernbrook St.Yonkers, NY 10705",Westchester County,(914) 963-9600 Ext,Transportation,407,407,3/16/2020,School closing mandated by the State of New Yo...,"Local 811 Warehouse, Production, Sales and All...",Temporary Plant Layoff
29,4/21/2020,2019-1525,Plant Layoff,GCT New York LP (Global Container Terminals USA),"300 Western AvenueStaten Island, NY 10303",Richmond County,(201) 779-4537 (work cell phone),Marine Cargo Handling,0,0,5/15/2020,Early contract termination by Maersk Lines. Th...,International Longshoreman’s Association (ILA)...,Plant Layoff
30,4/27/2020,2019-1582,Temporary Plant Layoff,"OS Restaurant Services, LLC (Bloomin Brands- O...",Multiple Central Region locations,Onondaga County,(813) 282-1225,Restaurant,0,174,3/15/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Layoff
31,4/27/2020,2019-1585,Temporary Plant Closing,"OS Restaurant Services, LLC (Bloomin Brands - ...",Multiple Capital Region locations,Albany/Saratoga/Warren County,(813) 282-1225,Restaurant,260,260,3/15/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Closing
32,4/27/2020,2019-1583,Temporary Plant Closing,"OS Restaurant Services, LLC (Bloomin Brands - ...",Multiple Finger Lakes Region locations,Monroe/Ontario County,(813) 282-1225,Restaurant,239,239,3/15/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Closing
33,4/27/2020,2019-1584,Temporary Plant Closing,"OS Restaurant Services, LLC (Bloomin Brands - ...",Multiple Western Region locations,Erie County,(813) 282-1225,Restaurant,289,289,3/15/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Closing
34,4/27/2020,2019-1586,Temporary Plant Closing,"OS Restaurant Services, LLC (Bloomin Brands - ...",Multiple Southern Region locations,Broome/Chemung County,(813) 282-1225,Restaurant,154,154,3/15/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Closing

In [188]:
df_na.groupby(['business_type'])['affected'].agg('sum').sort_values(ascending=False).reset_index()

TypeError: can only concatenate str (not "int") to str